# HOMEWORK_1 <a class="anchor" id="top"></a>
This homework is the first homwework of py4ds course. 
I am following this [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI).

## Before We Start
Installing and importing numpy.

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


## Table of Contents
1. [The Basics](#basics)
2. [Accessing/Changing Elements](#accessing)
3. [Initializing Different Types of Arrays](#initializing)

### The Basics <a class="anchor" id="basics"></a>
Creating arrays, shape, size, etc. 

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
# Get the dimension of the array
b.ndim

2

In [13]:
# Get the shape of the array
b.shape

(2, 3)

In [14]:
# Get the type of the array
b.dtype

dtype('int32')

In [19]:
# Get the size of the array
b.size

6

In [16]:
# Get the item size of the array
b.itemsize

4

In [20]:
# Get the total size of the array
b.nbytes

24

### Accessing/Changing Elements <a class="anchor" id="accessing"></a>
Whole rows, columns, etc.

In [21]:
array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
# Get a specific element [r, c]
array[1, 5]

12

In [28]:
# Get a specific row
array[0, :]

array([1, 2, 3, 4, 5, 6])

In [24]:
# Get a specific column
array[:, 2]

array([3, 9])

In [31]:
# Get a little more fancy [startindex:endindex:stepsize]
array[0, 1:-1:2]

array([2, 4])

In [36]:
# Replace a specific element
array[1, 5] = 20
array

array([[ 7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 20]])

In [37]:
# Replace a specific row
array[0, :] = [7, 8, 9, 10, 11, 12]
array

array([[ 7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 20]])

In [39]:
# Replace a specific column
array[:, 2] = [1, 2]
array

array([[ 7,  8,  1, 10, 11, 12],
       [ 7,  8,  2, 10, 11, 20]])

In [ ]:
# Get a specific element in a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

array_3d[0, 1, 1]

In [ ]:
# Replace a specific element in a 3D array
array_3d[0, 1, 1] = 20
print(array_3d)
print("=====================================")

# Replace a specific row in a 3D array
array_3d[0, 1, :] = [5, 6]
print(array_3d)
print("=====================================")

# Replace a specific column in a 3D array
array_3d[0, :, 1] = [3, 4]
print(array_3d)


### Initializing Different Types of Arrays <a class="anchor" id="initializing"></a>

1s, 0s, full, random, etc.