# HOMEWORK_1 <a class="anchor" id="top"></a>
This homework is the first homwework of py4ds course. 
I am following this [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI).

## Before We Start
Installing and importing numpy.

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


## Table of Contents
1. [The Basics](#basics)
2. [Accessing/Changing Elements](#accessing)
3. [Initializing Different Types of Arrays](#initializing)
4. [Be Careful When Copying Arrays](#copying)
5. [Mathematics](#mathematics)
6. [Linear Algebra](#linear-algebra)
7. [Statistics](#statistics)
8. [Reorganizing Arrays](#reorganizing-arrays)
9. [Miscellaneous](#miscellaneous)

### The Basics <a class="anchor" id="basics"></a>
Creating arrays, shape, size, etc. 

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# We can change the data type of the array by using dtype parameter for example: int16, int32, 
# int64, float32, etc.

[[1 2 3]
 [4 5 6]]


In [12]:
# Get the dimension of the array
b.ndim

2

In [13]:
# Get the shape of the array
b.shape

(2, 3)

In [14]:
# Get the type of the array
b.dtype

dtype('int32')

In [19]:
# Get the size of the array
b.size

6

In [16]:
# Get the item size of the array
b.itemsize

4

In [20]:
# Get the total size of the array
b.nbytes

24

### Accessing/Changing Elements <a class="anchor" id="accessing"></a>
Whole rows, columns, etc.

In [21]:
array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
# Get a specific element [r, c]
array[1, 5]

12

In [28]:
# Get a specific row
array[0, :]

array([1, 2, 3, 4, 5, 6])

In [24]:
# Get a specific column
array[:, 2]

array([3, 9])

In [31]:
# Get a little more fancy [startindex:endindex:stepsize]
array[0, 1:-1:2]

array([2, 4])

In [36]:
# Replace a specific element
array[1, 5] = 20
array

array([[ 7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 20]])

In [37]:
# Replace a specific row
array[0, :] = [7, 8, 9, 10, 11, 12]
array

array([[ 7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 20]])

In [39]:
# Replace a specific column
array[:, 2] = [1, 2]
array

array([[ 7,  8,  1, 10, 11, 12],
       [ 7,  8,  2, 10, 11, 20]])

In [ ]:
# Get a specific element in a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

array_3d[0, 1, 1]

In [ ]:
# Replace a specific element in a 3D array
array_3d[0, 1, 1] = 20
print(array_3d)
print("=====================================")

# Replace a specific row in a 3D array
array_3d[0, 1, :] = [5, 6]
print(array_3d)
print("=====================================")

# Replace a specific column in a 3D array
array_3d[0, :, 1] = [3, 4]
print(array_3d)


### Initializing Different Types of Arrays <a class="anchor" id="initializing"></a>

1s, 0s, full, random, etc.

In [51]:
# All zeros matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# All ones matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [53]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [54]:
# Any other number (full_like)
np.full_like(a, 4)

# We can use np.full with a.shape for the same result

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [56]:
# Random decimal numbers
np.random.rand(4, 2)

# We can use np.random.random_sample with a.shape for the same result

array([[0.77151891, 0.67903624],
       [0.05824805, 0.88648209],
       [0.56529495, 0.18754572],
       [0.51972336, 0.94302641]])

In [58]:
# Random integer values
np.random.randint(-4, 8, size=(3, 3))

array([[ 5,  5,  7],
       [ 1, -3,  1],
       [-1,  1,  1]])

In [59]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [67]:
# Challenge: Try to build a 5x5 matrix with 1s around the border and 0s inside and 9 in the middle
new_array = np.ones((5, 5))
new_array[1:4, 1:4] = 0
new_array[2, 2] = 9
new_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be Careful When Copying Arrays! <a class="anchor" id="copying"></a>

In [68]:
# We can copy arrays
a = np.array([1, 2, 3])
b = a.copy() 
# b = a will not work because b will be a reference to a
b[0] = 100
print(a)

[1 2 3]


### Mathematics <a class="anchor" id="mathematics"></a>
We can elementwise do arithmetic operations.

In [69]:
a = np.array([1, 2, 3, 4])

In [70]:
a + 2

array([3, 4, 5, 6])

In [71]:
a - 2

array([-1,  0,  1,  2])

In [72]:
a * 2

array([2, 4, 6, 8])

In [73]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [75]:
a ** 2

array([ 1,  4,  9, 16])

In [76]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra <a class="anchor" id="linear-algebra"></a>

In [78]:
a = np.full((2, 3), 2)
a

array([[2, 2, 2],
       [2, 2, 2]])

In [79]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
# Matrix multiplication
np.matmul(a, b)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [86]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

You can find more information about linear algebra here: https://numpy.org/doc/stable/reference/routines.linalg.html

### Statistics <a class="anchor" id="statistics"></a>

In [87]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
np.min(stats)

1

In [89]:
np.max(stats)

# You can also use np.min and np.max with axis parameter

6

In [90]:
np.sum(stats)

# You can also use np.sum with axis parameter

21

### Reorganizing Arrays <a class="anchor" id="reorganizing-arrays"></a>

In [91]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [93]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [94]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)

np.hstack([h1, h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous <a class="anchor" id="miscellaneous"></a>
Load data from a website

In [ ]:
%pip install requests

In [101]:
import requests

In [107]:
api_url = "https://animechan.vercel.app/api/random"
response = requests.get(api_url).json()
response
# No number in this response so we can't use numpy effectively

{'anime': 'Yami no Matsuei',
 'character': 'Kazutaka Muraki',
 'quote': "Humans are weak. For every cure found, another disease is uncovered. It's a game of chase."}

In [122]:
api_url = "https://api.coinlore.net/api/global/"
response = requests.get(api_url).json()
response
# Global cryptocurrency data

[{'coins_count': 10503,
  'active_markets': 29193,
  'total_mcap': 1247044615605.9094,
  'total_volume': 311862217348.7892,
  'btc_d': '42.46',
  'eth_d': '17.17',
  'mcap_change': '-2.84',
  'volume_change': '1.97',
  'avg_change_percent': '-0.61',
  'volume_ath': 344187126292427800,
  'mcap_ath': 8237181118976.519}]

In [163]:
coin_data = np.array([])
response_dict = response[0]
print(response_dict)
for key, value in response_dict.items():
    coin_data = np.append(coin_data, value)
coin_data
# There is a problem while trying to convert the elements to float

{'coins_count': 10503, 'active_markets': 29193, 'total_mcap': 1247044615605.9094, 'total_volume': 311862217348.7892, 'btc_d': '42.46', 'eth_d': '17.17', 'mcap_change': '-2.84', 'volume_change': '1.97', 'avg_change_percent': '-0.61', 'volume_ath': 344187126292427800, 'mcap_ath': 8237181118976.519}


array(['10503.0', '29193.0', '1247044615605.9094', '311862217348.7892',
       '42.46', '17.17', '-2.84', '1.97', '-0.61', '344187126292427800',
       '8237181118976.519'], dtype='<U32')

### Boolean Masking and Advanced Indexing <a class="anchor" id="bool-masking"></a>

In [149]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [150]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [151]:
# You can index with a list in NumPy!!
array[[2, 4, 6]]

array([3, 5, 7])

In [152]:
np.any(array > 5)
# We can use axis parameter as well

True

In [153]:
np.all(array > 5)
# Check if all elements are greater than 5

False

In [162]:
# Indexing challenge
a = np.random.randint(1, 10, size=(6, 5))
print(a)
print(a[2:4, 0:2])
print(a[[0,1,2,3], [1,2,3,4]])
print(a[[0,4,5], 3:])

[[2 2 8 2 4]
 [3 5 4 2 7]
 [6 1 2 4 3]
 [7 1 1 7 5]
 [3 1 2 5 5]
 [2 8 5 8 5]]
[[6 1]
 [7 1]]
[2 4 4 5]
[[2 4]
 [5 5]
 [8 5]]
