# HOMEWORK_1 <a class="anchor" id="top"></a>
This homework is the first homwework of py4ds course. 
I am following this [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI).

## Before We Start
Installing and importing numpy.

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


## Table of Contents
1. [The Basics](#basics)
2. [Accessing/Changing Elements](#accessing)
3. [Initializing Different Types of Arrays](#initializing)
4. [Be Careful When Copying Arrays](#copying)
5. [Mathematics](#mathematics)
6. [Linear Algebra](#linear-algebra)
7. [Statistics](#statistics)
8. [Reorganizing Arrays](#reorganizing-arrays)
9. [Miscellaneous](#miscellaneous)
10. [Boolean Masking and Advanced Indexing](#bool-masking)

### The Basics <a class="anchor" id="basics"></a>
Creating arrays, shape, size, etc. 

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# We can change the data type of the array by using dtype parameter for example: int16, int32, 
# int64, float32, etc.

[[1 2 3]
 [4 5 6]]


In [5]:
# Get the dimension of the array
b.ndim

2

In [6]:
# Get the shape of the array
b.shape

(2, 3)

In [7]:
# Get the type of the array
b.dtype

dtype('int32')

In [8]:
# Get the size of the array
b.size

6

In [9]:
# Get the item size of the array
b.itemsize

4

In [10]:
# Get the total size of the array
b.nbytes

24

### Accessing/Changing Elements <a class="anchor" id="accessing"></a>
Whole rows, columns, etc.

In [11]:
array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
# Get a specific element [r, c]
array[1, 5]

12

In [13]:
# Get a specific row
array[0, :]

array([1, 2, 3, 4, 5, 6])

In [14]:
# Get a specific column
array[:, 2]

array([3, 9])

In [15]:
# Get a little more fancy [startindex:endindex:stepsize]
array[0, 1:-1:2]

array([2, 4])

In [16]:
# Replace a specific element
array[1, 5] = 20
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 20]])

In [17]:
# Replace a specific row
array[0, :] = [7, 8, 9, 10, 11, 12]
array

array([[ 7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 20]])

In [18]:
# Replace a specific column
array[:, 2] = [1, 2]
array

array([[ 7,  8,  1, 10, 11, 12],
       [ 7,  8,  2, 10, 11, 20]])

In [19]:
# Get a specific element in a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

array_3d[0, 1, 1]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


4

In [20]:
# Replace a specific element in a 3D array
array_3d[0, 1, 1] = 20
print(array_3d)
print("=====================================")

# Replace a specific row in a 3D array
array_3d[0, 1, :] = [5, 6]
print(array_3d)
print("=====================================")

# Replace a specific column in a 3D array
array_3d[0, :, 1] = [3, 4]
print(array_3d)


[[[ 1  2]
  [ 3 20]]

 [[ 5  6]
  [ 7  8]]]
[[[1 2]
  [5 6]]

 [[5 6]
  [7 8]]]
[[[1 3]
  [5 4]]

 [[5 6]
  [7 8]]]


### Initializing Different Types of Arrays <a class="anchor" id="initializing"></a>

1s, 0s, full, random, etc.

In [21]:
# All zeros matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# All ones matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [23]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
# Any other number (full_like)
np.full_like(a, 4)

# We can use np.full with a.shape for the same result

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [25]:
# Random decimal numbers
np.random.rand(4, 2)

# We can use np.random.random_sample with a.shape for the same result

array([[0.37333583, 0.91413524],
       [0.05513822, 0.20893958],
       [0.01233508, 0.31110548],
       [0.46549632, 0.95143503]])

In [26]:
# Random integer values
np.random.randint(-4, 8, size=(3, 3))

array([[ 5,  4,  3],
       [ 6,  7,  5],
       [-4,  4, -2]])

In [27]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [29]:
# Challenge: Try to build a 5x5 matrix with 1s around the border and 0s inside and 9 in the middle
new_array = np.ones((5, 5))
new_array[1:4, 1:4] = 0
new_array[2, 2] = 9
new_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be Careful When Copying Arrays! <a class="anchor" id="copying"></a>

In [30]:
# We can copy arrays
a = np.array([1, 2, 3])
b = a.copy() 
# b = a will not work because b will be a reference to a
b[0] = 100
print(a)

[1 2 3]


### Mathematics <a class="anchor" id="mathematics"></a>
We can elementwise do arithmetic operations.

In [31]:
a = np.array([1, 2, 3, 4])

In [32]:
a + 2

array([3, 4, 5, 6])

In [33]:
a - 2

array([-1,  0,  1,  2])

In [34]:
a * 2

array([2, 4, 6, 8])

In [35]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [36]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [37]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra <a class="anchor" id="linear-algebra"></a>

In [39]:
a = np.full((2, 3), 2)
a

array([[2, 2, 2],
       [2, 2, 2]])

In [40]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# Matrix multiplication
np.matmul(a, b)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [42]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

You can find more information about linear algebra here: https://numpy.org/doc/stable/reference/routines.linalg.html

### Statistics <a class="anchor" id="statistics"></a>

In [43]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.min(stats)

1

In [45]:
np.max(stats)

# You can also use np.min and np.max with axis parameter

6

In [46]:
np.sum(stats)

# You can also use np.sum with axis parameter

21

### Reorganizing Arrays <a class="anchor" id="reorganizing-arrays"></a>

In [47]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [49]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)

np.hstack([h1, h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous <a class="anchor" id="miscellaneous"></a>
Load data from a website

In [51]:
%pip install requests

Note: you may need to restart the kernel to use updated packages.


In [52]:
import requests

In [53]:
api_url = "https://animechan.vercel.app/api/random"
response = requests.get(api_url).json()
response
# No number in this response so we can't use numpy effectively

{'anime': 'One Outs',
 'character': 'Toua Tokuchi',
 'quote': 'Winning a game is not dependent on surpassing your opponents with your strength or waiting for lucky breaks. Conquer the opponent, crushing them, and stepping over the fallen ones ruthlessly. Winning means dominating over countless dead bodies.'}

In [54]:
api_url = "https://api.coinlore.net/api/global/"
response = requests.get(api_url).json()
response
# Global cryptocurrency data

[{'coins_count': 10503,
  'active_markets': 29010,
  'total_mcap': 1284405782156.1323,
  'total_volume': 214321751812.5829,
  'btc_d': '42.74',
  'eth_d': '17.43',
  'mcap_change': '1.31',
  'volume_change': '1.25',
  'avg_change_percent': '0.36',
  'volume_ath': 344187126292427800,
  'mcap_ath': 8237181118976.519}]

In [55]:
coin_data = np.array([])
response_dict = response[0]
print(response_dict)
for key, value in response_dict.items():
    print(type(value) , value)
    coin_data = np.append(coin_data, float(value))
coin_data.astype("int64")
# Problem solved  

{'coins_count': 10503, 'active_markets': 29010, 'total_mcap': 1284405782156.1323, 'total_volume': 214321751812.5829, 'btc_d': '42.74', 'eth_d': '17.43', 'mcap_change': '1.31', 'volume_change': '1.25', 'avg_change_percent': '0.36', 'volume_ath': 344187126292427800, 'mcap_ath': 8237181118976.519}
<class 'int'> 10503
<class 'int'> 29010
<class 'float'> 1284405782156.1323
<class 'float'> 214321751812.5829
<class 'str'> 42.74
<class 'str'> 17.43
<class 'str'> 1.31
<class 'str'> 1.25
<class 'str'> 0.36
<class 'int'> 344187126292427800
<class 'float'> 8237181118976.519


array([             10503,              29010,      1284405782156,
             214321751812,                 42,                 17,
                        1,                  1,                  0,
       344187126292427776,      8237181118976], dtype=int64)

### Boolean Masking and Advanced Indexing <a class="anchor" id="bool-masking"></a>

In [56]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [58]:
# You can index with a list in NumPy!!
array[[2, 4, 6]]

array([3, 5, 7])

In [59]:
np.any(array > 5)
# We can use axis parameter as well

True

In [60]:
np.all(array > 5)
# Check if all elements are greater than 5

False

In [61]:
# Indexing challenge
a = np.random.randint(1, 10, size=(6, 5))
print(a)
print(a[2:4, 0:2])
print(a[[0,1,2,3], [1,2,3,4]])
print(a[[0,4,5], 3:])

[[2 3 3 1 8]
 [7 9 1 1 1]
 [5 4 5 3 4]
 [1 3 4 1 8]
 [6 8 6 4 8]
 [7 4 8 6 2]]
[[5 4]
 [1 3]]
[3 1 3 8]
[[1 8]
 [4 8]
 [6 2]]
